var cities = ["Karachi", "Lahore", "Islamabad", "Quetta", "Peshawar"];
document.write("Cities List :");
document.write("<br>");
document.write(cities);
document.write("<br>");
document.write("<br>");
var selectedCities = cities.slice(2,4);
document.write("Selected Cities List :");
document.write("<br>");
document.write(selectedCities);